INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UNIT','考察团 #{1_ID}：己方，位置 ({2_X}, {3_Y})。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OPEN','人文考察·验证'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TITLE','人文考察团：N1 原型记录'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CLOSE','关闭'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_INTRO','当前仍是旧验证原型，可步行、遇敌撤退；正式考察团将仅通过任务派遣，并要求单位共存。新行为尚未实现。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CREATE','创建验证团'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_REFRESH','刷新报告'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TRAVEL','读取派遣耗时（不移动）'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ARM','记录原型位置'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_END','结束并移除验证团'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_END_HINT','只移除本验证团，不影响其它单位。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NO_TARGET','暂无可读目标（已遇见且已揭示的外国首都）'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_INITIAL','先选中己方文化 ACTIVE IV 城市，再创建验证团。城中心需没有其它平民单位。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OWN_CITY','请先在地图上选中己方城市。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CULTURE_IV','创建验证团需要当前文化 ACTIVE IV，且没有待确认投资。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OCCUPIED','城中心已有平民单位，请先移开。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CAP','已有验证团，不能再创建。点击刷新查看；完成后可结束验证。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_HELD','原生创建结果不明确，已阻止再次创建。请停止本次验证并回传报告；不要反复点击。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TEAM_CHANGED','验证团不可用或已变化。请先刷新；不要用其它单位替代。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_END_FAILED','移除未得到确认。请停止并回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_DB','验证单位数据库未加载或不符合保护配置，请停止并回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ERROR','当前操作未完成：{1_Reason}。请停止并回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_COUNT','验证团：{1_Count}／1（免费原型，不是正式训练）。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ENDED','验证团已移除。本批没有写入城市历史或发放收益。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_MISSING','原单位已不在原Owner名下：尚不能确认保护成功。不要重建单位掩盖结果，请回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_WATCH','标记单位 #{1_ID} 仍属于原Owner：标记位置 ({2_X}, {3_Y}) → 当前 ({4_X}, {5_Y})。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_WATCH_NOTE','位置变化不自动证明撤退，需结合实际操作判断。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CAPACITY','间谍容量：创建前 {1_Before} → 当前 {2_After}（?＝未读到）。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMING','目标：{1_City}；原生旅行 {2_Travel} 回合，建立 {3_Establish} 回合，合计 {4_Total}。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMING_SCOPE','第 {1_Turn} 回合读取；只显示耗时，未执行派遣。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMING_UNKNOWN','耗时接口未确认：{1_Reason}。停止此路径并回传；不会改走原生间谍操作或自行编造回合数。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_STOP_HINT','B180接敌撤退已记录，正式考察团改用共存方向。无需重复接敌测试；本窗口仍可读取和清理旧原型。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_WAIT','正在等待本次请求结果，请勿重复点击。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMEOUT','等待结果超时。请点击刷新核对单位；不会自动重发创建请求。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_SEND_ERROR','请求未确认：{1_Error}。先刷新核对，不自动重发。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UNIT','考察团 #{1_ID}：己方，位置 ({2_X}, {3_Y})。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OPEN','人文考察·验证'),
('en_US','LOC_SPC_EXPEDITION_GATE_TITLE','人文考察团：N1 原型记录'),
('en_US','LOC_SPC_EXPEDITION_GATE_CLOSE','关闭'),
('en_US','LOC_SPC_EXPEDITION_GATE_INTRO','当前仍是旧验证原型，可步行、遇敌撤退；正式考察团将仅通过任务派遣，并要求单位共存。新行为尚未实现。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CREATE','创建验证团'),
('en_US','LOC_SPC_EXPEDITION_GATE_REFRESH','刷新报告'),
('en_US','LOC_SPC_EXPEDITION_GATE_TRAVEL','读取派遣耗时（不移动）'),
('en_US','LOC_SPC_EXPEDITION_GATE_ARM','记录原型位置'),
('en_US','LOC_SPC_EXPEDITION_GATE_END','结束并移除验证团'),
('en_US','LOC_SPC_EXPEDITION_GATE_END_HINT','只移除本验证团，不影响其它单位。'),
('en_US','LOC_SPC_EXPEDITION_GATE_NO_TARGET','暂无可读目标（已遇见且已揭示的外国首都）'),
('en_US','LOC_SPC_EXPEDITION_GATE_INITIAL','先选中己方文化 ACTIVE IV 城市，再创建验证团。城中心需没有其它平民单位。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OWN_CITY','请先在地图上选中己方城市。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CULTURE_IV','创建验证团需要当前文化 ACTIVE IV，且没有待确认投资。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OCCUPIED','城中心已有平民单位，请先移开。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CAP','已有验证团，不能再创建。点击刷新查看；完成后可结束验证。'),
('en_US','LOC_SPC_EXPEDITION_GATE_HELD','原生创建结果不明确，已阻止再次创建。请停止本次验证并回传报告；不要反复点击。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TEAM_CHANGED','验证团不可用或已变化。请先刷新；不要用其它单位替代。'),
('en_US','LOC_SPC_EXPEDITION_GATE_END_FAILED','移除未得到确认。请停止并回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_DB','验证单位数据库未加载或不符合保护配置，请停止并回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_ERROR','当前操作未完成：{1_Reason}。请停止并回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_COUNT','验证团：{1_Count}／1（免费原型，不是正式训练）。'),
('en_US','LOC_SPC_EXPEDITION_GATE_ENDED','验证团已移除。本批没有写入城市历史或发放收益。'),
('en_US','LOC_SPC_EXPEDITION_GATE_MISSING','原单位已不在原Owner名下：尚不能确认保护成功。不要重建单位掩盖结果，请回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_WATCH','标记单位 #{1_ID} 仍属于原Owner：标记位置 ({2_X}, {3_Y}) → 当前 ({4_X}, {5_Y})。'),
('en_US','LOC_SPC_EXPEDITION_GATE_WATCH_NOTE','位置变化不自动证明撤退，需结合实际操作判断。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CAPACITY','间谍容量：创建前 {1_Before} → 当前 {2_After}（?＝未读到）。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMING','目标：{1_City}；原生旅行 {2_Travel} 回合，建立 {3_Establish} 回合，合计 {4_Total}。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMING_SCOPE','第 {1_Turn} 回合读取；只显示耗时，未执行派遣。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMING_UNKNOWN','耗时接口未确认：{1_Reason}。停止此路径并回传；不会改走原生间谍操作或自行编造回合数。'),
('en_US','LOC_SPC_EXPEDITION_GATE_STOP_HINT','B180接敌撤退已记录，正式考察团改用共存方向。无需重复接敌测试；本窗口仍可读取和清理旧原型。'),
('en_US','LOC_SPC_EXPEDITION_GATE_WAIT','正在等待本次请求结果，请勿重复点击。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMEOUT','等待结果超时。请点击刷新核对单位；不会自动重发创建请求。'),
('en_US','LOC_SPC_EXPEDITION_GATE_SEND_ERROR','请求未确认：{1_Error}。先刷新核对，不自动重发。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UNIT_NAME','人文考察团（验证）'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_DESCRIPTION','N1技术验证单位：非间谍，采用原生被捕撤退标志。免费测试创建；不提供正式任务或收益。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UNIT_NAME','人文考察团（验证）'),
('en_US','LOC_SPC_EXPEDITION_GATE_DESCRIPTION','N1技术验证单位：非间谍，采用原生被捕撤退标志。免费测试创建；不提供正式任务或收益。');

-- B179: P0 entry and readable unavailable state; Chinese remains the UI language.
INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UI_UNAVAILABLE','人文考察验证窗口尚未就绪（{1_Version}）。请停止并回传此提示；本次没有创建单位。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UI_UNAVAILABLE','人文考察验证窗口尚未就绪（{1_Version}）。请停止并回传此提示；本次没有创建单位。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_PANEL_HINT','选中城市后查看专业与文化报告。人文考察团测试请点击右下方“人文考察·验证”。[NEWLINE]已完成阶段的诊断入口暂时隐藏，相关能力仍正常运行。'),
('en_US','LOC_SPC_EXPEDITION_GATE_PANEL_HINT','选中城市后查看专业与文化报告。人文考察团测试请点击右下方“人文考察·验证”。[NEWLINE]已完成阶段的诊断入口暂时隐藏，相关能力仍正常运行。');

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
('zh_Hans_CN', 'LOC_SPC_EXPEDITION_GATE_UI_OPEN_FAILED', '人文考察验证窗口未能打开，当前面板已保留。请截图此提示并暂停本项测试；不要重复点击创建单位。'),
('en_US', 'LOC_SPC_EXPEDITION_GATE_UI_OPEN_FAILED', '人文考察验证窗口未能打开，当前面板已保留。请截图此提示并暂停本项测试；不要重复点击创建单位。');

-- B181: readable target navigation; no glyph-only arrows.
INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_PREVIOUS','上一目标'),
('en_US','LOC_SPC_EXPEDITION_GATE_PREVIOUS','上一目标'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NEXT','下一目标'),
('en_US','LOC_SPC_EXPEDITION_GATE_NEXT','下一目标');
