INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UNIT','考察团 #{1_ID}：己方，位置 ({2_X}, {3_Y})。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OPEN','人文考察·验证'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TITLE','人文考察团：Spy=0 派遣与共存验证'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CLOSE','关闭'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_INTRO','独立容量与来源绑定；只通过本窗口派遣。等待期间暂留原地，到期尝试抵达外国城中心；无任务奖励。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CREATE','① 创建原型'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_REFRESH','刷新报告'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TRAVEL','② 检查原生接口'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ARM','③ 开始独立派遣'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_END','结束并移除验证团'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_END_HINT','只移除本验证团，不影响其它单位。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NO_TARGET','暂无可读目标（已遇见且已揭示的外国首都）'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_INITIAL','选中己方文化 ACTIVE IV 城市后创建。可在城中心保留一个普通平民，观察是否能共存。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OWN_CITY','请先在地图上选中己方城市。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CULTURE_IV','创建验证团需要当前文化 ACTIVE IV，且没有待确认投资。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OCCUPIED','城中心已有平民单位，请先移开。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CAP','已有验证团，不能再创建。点击刷新查看；完成后可结束验证。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_HELD','原型已暂停，不能继续派遣或重复创建。请回传报告；不会补造、撤退或猜测单位位置。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TEAM_CHANGED','验证团不可用或已变化。请先刷新；不要用其它单位替代。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_END_FAILED','移除未得到确认。请停止并回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_DB','验证单位数据库未加载或不符合保护配置，请停止并回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ERROR','当前操作未完成：{1_Reason}。请停止并回传报告。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_COUNT','验证团：{1_Count}／1（免费原型，不是正式训练）。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ENDED','验证团已移除。本批没有写入城市历史或发放收益。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_MISSING','原单位不再属于原Owner或类型已变。测试停止，不创建替代单位。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_WATCH','标记单位 #{1_ID} 仍属于原Owner：标记位置 ({2_X}, {3_Y}) → 当前 ({4_X}, {5_Y})。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_WATCH_NOTE','位置变化不自动证明撤退，需结合实际操作判断。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_CAPACITY','间谍容量：创建前 {1_Before} → 当前 {2_After}（?＝未读到）。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMING','目标：{1_City}；原生旅行 {2_Travel} 回合，建立 {3_Establish} 回合，合计 {4_Total}。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMING_SCOPE','第 {1_Turn} 回合读数；实际派遣由本 Mod 计时，不提交原生间谍操作。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMING_UNKNOWN','耗时接口未确认：{1_Reason}。停止此路径并回传；不会改走原生间谍操作或自行编造回合数。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_STOP_HINT','创建/到达后检查双方单位是否仍在原位；接敌仍需观察。若位移、消失、捕获或暂停，请停止。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_WAIT','正在等待本次请求结果，请勿重复点击。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_TIMEOUT','等待结果超时。请点击刷新核对单位；不会自动重发创建请求。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_SEND_ERROR','请求未确认：{1_Error}。先刷新核对，不自动重发。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UNIT','考察团 #{1_ID}：己方，位置 ({2_X}, {3_Y})。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OPEN','人文考察·验证'),
('en_US','LOC_SPC_EXPEDITION_GATE_TITLE','人文考察团：Spy=0 派遣与共存验证'),
('en_US','LOC_SPC_EXPEDITION_GATE_CLOSE','关闭'),
('en_US','LOC_SPC_EXPEDITION_GATE_INTRO','独立容量与来源绑定；只通过本窗口派遣。等待期间暂留原地，到期尝试抵达外国城中心；无任务奖励。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CREATE','① 创建原型'),
('en_US','LOC_SPC_EXPEDITION_GATE_REFRESH','刷新报告'),
('en_US','LOC_SPC_EXPEDITION_GATE_TRAVEL','② 检查原生接口'),
('en_US','LOC_SPC_EXPEDITION_GATE_ARM','③ 开始独立派遣'),
('en_US','LOC_SPC_EXPEDITION_GATE_END','结束并移除验证团'),
('en_US','LOC_SPC_EXPEDITION_GATE_END_HINT','只移除本验证团，不影响其它单位。'),
('en_US','LOC_SPC_EXPEDITION_GATE_NO_TARGET','暂无可读目标（已遇见且已揭示的外国首都）'),
('en_US','LOC_SPC_EXPEDITION_GATE_INITIAL','选中己方文化 ACTIVE IV 城市后创建。可在城中心保留一个普通平民，观察是否能共存。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OWN_CITY','请先在地图上选中己方城市。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CULTURE_IV','创建验证团需要当前文化 ACTIVE IV，且没有待确认投资。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OCCUPIED','城中心已有平民单位，请先移开。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CAP','已有验证团，不能再创建。点击刷新查看；完成后可结束验证。'),
('en_US','LOC_SPC_EXPEDITION_GATE_HELD','原型已暂停，不能继续派遣或重复创建。请回传报告；不会补造、撤退或猜测单位位置。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TEAM_CHANGED','验证团不可用或已变化。请先刷新；不要用其它单位替代。'),
('en_US','LOC_SPC_EXPEDITION_GATE_END_FAILED','移除未得到确认。请停止并回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_DB','验证单位数据库未加载或不符合保护配置，请停止并回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_ERROR','当前操作未完成：{1_Reason}。请停止并回传报告。'),
('en_US','LOC_SPC_EXPEDITION_GATE_COUNT','验证团：{1_Count}／1（免费原型，不是正式训练）。'),
('en_US','LOC_SPC_EXPEDITION_GATE_ENDED','验证团已移除。本批没有写入城市历史或发放收益。'),
('en_US','LOC_SPC_EXPEDITION_GATE_MISSING','原单位不再属于原Owner或类型已变。测试停止，不创建替代单位。'),
('en_US','LOC_SPC_EXPEDITION_GATE_WATCH','标记单位 #{1_ID} 仍属于原Owner：标记位置 ({2_X}, {3_Y}) → 当前 ({4_X}, {5_Y})。'),
('en_US','LOC_SPC_EXPEDITION_GATE_WATCH_NOTE','位置变化不自动证明撤退，需结合实际操作判断。'),
('en_US','LOC_SPC_EXPEDITION_GATE_CAPACITY','间谍容量：创建前 {1_Before} → 当前 {2_After}（?＝未读到）。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMING','目标：{1_City}；原生旅行 {2_Travel} 回合，建立 {3_Establish} 回合，合计 {4_Total}。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMING_SCOPE','第 {1_Turn} 回合读数；实际派遣由本 Mod 计时，不提交原生间谍操作。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMING_UNKNOWN','耗时接口未确认：{1_Reason}。停止此路径并回传；不会改走原生间谍操作或自行编造回合数。'),
('en_US','LOC_SPC_EXPEDITION_GATE_STOP_HINT','创建/到达后检查双方单位是否仍在原位；接敌仍需观察。若位移、消失、捕获或暂停，请停止。'),
('en_US','LOC_SPC_EXPEDITION_GATE_WAIT','正在等待本次请求结果，请勿重复点击。'),
('en_US','LOC_SPC_EXPEDITION_GATE_TIMEOUT','等待结果超时。请点击刷新核对单位；不会自动重发创建请求。'),
('en_US','LOC_SPC_EXPEDITION_GATE_SEND_ERROR','请求未确认：{1_Error}。先刷新核对，不自动重发。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UNIT_NAME','人文考察团（验证）'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_DESCRIPTION','N1技术验证单位：非间谍，采用原生被捕撤退标志。免费测试创建；不提供正式任务或收益。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UNIT_NAME','人文考察团（验证）'),
('en_US','LOC_SPC_EXPEDITION_GATE_DESCRIPTION','N1技术验证单位：非间谍，采用原生被捕撤退标志。免费测试创建；不提供正式任务或收益。');

-- B179: P0 entry and readable unavailable state; Chinese remains the UI language.
INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UI_UNAVAILABLE','人文考察验证窗口尚未就绪（{1_Version}）。请停止并回传此提示；本次没有创建单位。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UI_UNAVAILABLE','人文考察验证窗口尚未就绪（{1_Version}）。请停止并回传此提示；本次没有创建单位。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_PANEL_HINT','选中城市后查看专业与文化报告。人文考察团测试请点击右下方“人文考察·验证”。[NEWLINE]已完成阶段的诊断入口暂时隐藏，相关能力仍正常运行。'),
('en_US','LOC_SPC_EXPEDITION_GATE_PANEL_HINT','选中城市后查看专业与文化报告。人文考察团测试请点击右下方“人文考察·验证”。[NEWLINE]已完成阶段的诊断入口暂时隐藏，相关能力仍正常运行。');

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
('zh_Hans_CN', 'LOC_SPC_EXPEDITION_GATE_UI_OPEN_FAILED', '人文考察验证窗口未能打开，当前面板已保留。请截图此提示并暂停本项测试；不要重复点击创建单位。'),
('en_US', 'LOC_SPC_EXPEDITION_GATE_UI_OPEN_FAILED', '人文考察验证窗口未能打开，当前面板已保留。请截图此提示并暂停本项测试；不要重复点击创建单位。');

-- B181: readable target navigation; no glyph-only arrows.
INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_PREVIOUS','上一目标'),
('en_US','LOC_SPC_EXPEDITION_GATE_PREVIOUS','上一目标'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NEXT','下一目标'),
('en_US','LOC_SPC_EXPEDITION_GATE_NEXT','下一目标');

-- B182: narrow independent dispatch diagnostics.
INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_LEGACY','这是旧撤退原型。请先“结束并移除验证团”，再创建 Spy=0 新原型。'),
('en_US','LOC_SPC_EXPEDITION_GATE_LEGACY','这是旧撤退原型。请先“结束并移除验证团”，再创建 Spy=0 新原型。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_UNBOUND','此团没有本次会话的可靠来源绑定（如读档后）。仍占容量，只能显式结束；不会猜测恢复。'),
('en_US','LOC_SPC_EXPEDITION_GATE_UNBOUND','此团没有本次会话的可靠来源绑定（如读档后）。仍占容量，只能显式结束；不会猜测恢复。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_SOURCE','来源：{1_City}（城市 #{2_ID}）；绑定保持，不随当前选城改变。'),
('en_US','LOC_SPC_EXPEDITION_GATE_SOURCE','来源：{1_City}（城市 #{2_ID}）；绑定保持，不随当前选城改变。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_JOURNEY','派遣中 → {1_City}：预计第 {2_Due} 回合抵达，剩余 {3_Left} 回合。原型等待期间留在出发地。'),
('en_US','LOC_SPC_EXPEDITION_GATE_JOURNEY','派遣中 → {1_City}：预计第 {2_Due} 回合抵达，剩余 {3_Left} 回合。原型等待期间留在出发地。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_ARRIVED','已精确抵达 {1_City}；到达时检查了 {2_Count} 个原有单位，未发现位移或消失。'),
('en_US','LOC_SPC_EXPEDITION_GATE_ARRIVED','已精确抵达 {1_City}；到达时检查了 {2_Count} 个原有单位，未发现位移或消失。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_READY','单位已绑定。请检查右键不能步行，再选择目标并开始独立派遣。'),
('en_US','LOC_SPC_EXPEDITION_GATE_READY','单位已绑定。请检查右键不能步行，再选择目标并开始独立派遣。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_COLOCATED','当前同格其它单位：{1_Count}。同格读数本身不证明接敌免疫。'),
('en_US','LOC_SPC_EXPEDITION_GATE_COLOCATED','当前同格其它单位：{1_Count}。同格读数本身不证明接敌免疫。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NATIVE_UNKNOWN','原生间谍旅行操作：无法读取资格；不会提交该操作。'),
('en_US','LOC_SPC_EXPEDITION_GATE_NATIVE_UNKNOWN','原生间谍旅行操作：无法读取资格；不会提交该操作。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NATIVE_ALLOWED','原生间谍旅行操作：资格查询允许；尚未执行，不能据此判定安全。'),
('en_US','LOC_SPC_EXPEDITION_GATE_NATIVE_ALLOWED','原生间谍旅行操作：资格查询允许；尚未执行，不能据此判定安全。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_NATIVE_REJECTED','原生间谍旅行操作：资格查询拒绝。原因未由引擎说明；独立派遣仍可测试。'),
('en_US','LOC_SPC_EXPEDITION_GATE_NATIVE_REJECTED','原生间谍旅行操作：资格查询拒绝。原因未由引擎说明；独立派遣仍可测试。'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_ZERO_NAME','人文考察团（Spy=0原型）'),
('en_US','LOC_SPC_EXPEDITION_ZERO_NAME','人文考察团（Spy=0原型）'),
('zh_Hans_CN','LOC_SPC_EXPEDITION_ZERO_DESCRIPTION','独立派遣与共存测试；不参加间谍任务，不发放奖励。'),
('en_US','LOC_SPC_EXPEDITION_ZERO_DESCRIPTION','独立派遣与共存测试；不参加间谍任务，不发放奖励。');

INSERT OR REPLACE INTO LocalizedText(Language,Tag,Text) VALUES
('zh_Hans_CN','LOC_SPC_EXPEDITION_GATE_OCCUPANCY_UNKNOWN','无法读取同格单位，不能判断共存结果。'),
('en_US','LOC_SPC_EXPEDITION_GATE_OCCUPANCY_UNKNOWN','无法读取同格单位，不能判断共存结果。');
