"""Reproducible native modifier table (stable B055 carrier identities). No rounding policy: pass full float text.
Formal D0017 weights; changing config requires regeneration.
Run --check for a read-only reproducibility check; --write explicitly regenerates.
"""
from pathlib import Path
import math, argparse
MAX_RECIPIENTS=129  # NetworkBridge: <=128 routes' destinations + capital self
LEVEL_WEIGHTS=(1,2,3,4)
K={'RESEARCH':1.0,'CULTURE':1.0}
def render():
    sql=['-- Generated by tools/generate_boost.py; B056 formal level weights; native fractional handling unchanged.']
    lua=['-- Generated with SQL; formal D0017 profile.', 'SPCBoostConfig={maxRecipients='+str(MAX_RECIPIENTS)+',weights={'+','.join(map(str,LEVEL_WEIGHTS))+'},k={'+','.join(k+'='+repr(v) for k,v in K.items())+'},rows={}}']
    for kind,target,prop in [('RESEARCH','CIVIC','Civic'),('CULTURE','TECHNOLOGY','Tech')]:
        for level,weight in enumerate(LEVEL_WEIGHTS,1):
            for n in range(1,MAX_RECIPIENTS+1):
                amount=repr(K[kind]*weight*math.sqrt(n));m=f'SPC_B055_{kind}_{level}_{n}';b='BUILDING_'+m
                sql.extend([
                  f"INSERT INTO Types(Type,Kind) VALUES ('{b}','KIND_BUILDING');",
                  f"INSERT INTO Buildings(BuildingType,Name,Cost,PrereqDistrict,InternalOnly,CitizenSlots,Housing) VALUES ('{b}','Specialization network boost',1,'DISTRICT_CITY_CENTER',1,0,0);",
                  f"INSERT INTO Modifiers(ModifierId,ModifierType) VALUES ('{m}','MODIFIER_PLAYER_ADJUST_{target}_BOOST'),('{m}_HD','MODIFIER_PLAYER_ADJUST_PROPERTY');",
                  f"INSERT INTO ModifierArguments(ModifierId,Name,Value) VALUES ('{m}','Amount','{amount}'),('{m}_HD','Key','HD_Player_Extra_{prop}_Boost'),('{m}_HD','Amount','{amount}');",
                  f"INSERT INTO BuildingModifiers(BuildingType,ModifierId) VALUES ('{b}','{m}'),('{b}','{m}_HD');"])
                lua.append(f"SPCBoostConfig.rows['{kind}:{level}:{n}']={{building='{b}',amount={amount}}}")
    return {'Mod/Data/NetworkBoost.sql':'\n'.join(sql)+'\n','Mod/BoostConfig.lua':'\n'.join(lua)+'\n'}
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');p.add_argument('--check',action='store_true');a=p.parse_args();root=Path(__file__).resolve().parents[1]
    for name,text in render().items():
        if a.write:(root/name).write_text(text)
        else:assert (root/name).read_text()==text,name
    print('B056 generated SQL/Lua: MATCH' if not a.write else 'B056 generated SQL/Lua: WRITTEN')
