-- P0-A: reviewed ordinary ontology, NOT Standardization activation policy.
-- Supported named base/HD infrastructure only; unknown rows never auto-enroll.
-- Native/HD tier data is adapter evidence. No database writes or yield carriers.
SPCOrdinaryBuildingCatalog={}
local M=SPCOrdinaryBuildingCatalog
M.REVISION='D0035-B164-2'
local known={
 ['BUILDING_HD_BUS_STOP']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_HD_MANSION']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_HD_VILLA']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_FAIR']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_HD_ART_PUBLISHING_HOUSE']='DISTRICT_THEATER',
 ['BUILDING_HD_DATA_CENTER']='DISTRICT_CAMPUS',
 ['BUILDING_HD_ELECTRONICS_FACTORY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_HD_INTERNET_COMPANY']='DISTRICT_INDUSTRIAL_ZONE',

 ['BUILDING_AMPHITHEATER']='DISTRICT_THEATER',
 ['BUILDING_ARMORY']='DISTRICT_ENCAMPMENT',
 ['BUILDING_BANK']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_BARRACKS']='DISTRICT_ENCAMPMENT',
 ['BUILDING_BASILIKOI_PAIDES']='DISTRICT_ENCAMPMENT',
 ['BUILDING_BROADCAST_CENTER']='DISTRICT_THEATER',
 ['BUILDING_CATHEDRAL']='DISTRICT_HOLY_SITE',
 ['BUILDING_CHANCERY']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_COAL_POWER_PLANT']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_CONSULATE']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_DAR_E_MEHR']='DISTRICT_HOLY_SITE',
 ['BUILDING_ELECTRONICS_FACTORY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_FACTORY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_FILM_STUDIO']='DISTRICT_THEATER',
 ['BUILDING_FOOD_MARKET']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_FOSSIL_FUEL_POWER_PLANT']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_GOV_CITYSTATES']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_CONQUEST']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_CULTURE']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_FAITH']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_MILITARY']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_SCIENCE']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_SPIES']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_TALL']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_WIDE']='DISTRICT_GOVERNMENT',
 ['BUILDING_GRAND_BAZAAR']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_GURDWARA']='DISTRICT_HOLY_SITE',
 ['BUILDING_HD_INN']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_HD_REGIONAL_COUNCIL_CENTER']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_HD_TAVERN']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_IZ_WATER_MILL']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_ACADEMY']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_ALTAR']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_ARCHITECTURE']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_ARSENAL']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_ART_GALLERY']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_ASSEMBLY']='DISTRICT_THEATER',
 ['BUILDING_JNR_CABINET']='DISTRICT_THEATER',
 ['BUILDING_JNR_CANDI']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_CAVALIER']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_CHEMICAL']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_COMMODITY_EXCHANGE']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_CRUISE_TERMINAL']='DISTRICT_HARBOR',
 ['BUILDING_JNR_DAOGUAN']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_DEPOT']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_EDUCATION']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_FREEPORT']='DISTRICT_HARBOR',
 ['BUILDING_JNR_FREIGHT_YARD']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_GARDEN']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_GRAND_HOTEL']='DISTRICT_THEATER',
 ['BUILDING_JNR_GUILDHALL']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_HAVEN']='DISTRICT_HARBOR',
 ['BUILDING_JNR_HOSPITAL']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_HOSPITIUM']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_JINJA']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_KHALWAT']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_LABORATORY']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_LIBERAL_ARTS']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_LIGHTHOUSE_TRADE']='DISTRICT_HARBOR',
 ['BUILDING_JNR_MANDIR']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_MANSION']='DISTRICT_THEATER',
 ['BUILDING_JNR_MANUFACTURY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_MARKETING_AGENCY']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_MBARI']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_MEDIA_CENTER']='DISTRICT_THEATER',
 ['BUILDING_JNR_MEDITATION']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_MERCHANT_QUARTER']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_MINT']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_MONASTERY']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_NAVAL_BASE']='DISTRICT_HARBOR',
 ['BUILDING_JNR_OPERA']='DISTRICT_THEATER',
 ['BUILDING_JNR_PERIPTEROS']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_PRISON']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_REAL_ACADEMY']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_RECYCLING_PLANT']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_SCHOOL']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_SOBOR']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_TARGET_RANGE']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_TOOLING_SHOP']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_TRANSIT_HUB']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_TZACUALLI']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_WAYSTATION']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_WIND_MILL']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_LIBRARY']='DISTRICT_CAMPUS',
 ['BUILDING_LIGHTHOUSE']='DISTRICT_HARBOR',
 ['BUILDING_MADRASA']='DISTRICT_CAMPUS',
 ['BUILDING_MARAE']='DISTRICT_THEATER',
 ['BUILDING_MARKET']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_MEETING_HOUSE']='DISTRICT_HOLY_SITE',
 ['BUILDING_MILITARY_ACADEMY']='DISTRICT_ENCAMPMENT',
 ['BUILDING_MOSQUE']='DISTRICT_HOLY_SITE',
 ['BUILDING_MUSEUM_ART']='DISTRICT_THEATER',
 ['BUILDING_MUSEUM_ARTIFACT']='DISTRICT_THEATER',
 ['BUILDING_NAVIGATION_SCHOOL']='DISTRICT_CAMPUS',
 ['BUILDING_ORDU']='DISTRICT_ENCAMPMENT',
 ['BUILDING_PAGODA']='DISTRICT_HOLY_SITE',
 ['BUILDING_POWER_PLANT']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_PRASAT']='DISTRICT_HOLY_SITE',
 ['BUILDING_QUEENS_BIBLIOTHEQUE']='DISTRICT_GOVERNMENT',
 ['BUILDING_RESEARCH_LAB']='DISTRICT_CAMPUS',
 ['BUILDING_SEAPORT']='DISTRICT_HARBOR',
 ['BUILDING_SHIPYARD']='DISTRICT_HARBOR',
 ['BUILDING_SHOPPING_MALL']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_SHRINE']='DISTRICT_HOLY_SITE',
 ['BUILDING_STABLE']='DISTRICT_ENCAMPMENT',
 ['BUILDING_STAVE_CHURCH']='DISTRICT_HOLY_SITE',
 ['BUILDING_STOCK_EXCHANGE']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_STUPA']='DISTRICT_HOLY_SITE',
 ['BUILDING_SUKIENNICE']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_SYNAGOGUE']='DISTRICT_HOLY_SITE',
 ['BUILDING_TEMPLE']='DISTRICT_HOLY_SITE',
 ['BUILDING_UNIVERSITY']='DISTRICT_CAMPUS',
 ['BUILDING_WAT']='DISTRICT_HOLY_SITE',
 ['BUILDING_WORKSHOP']='DISTRICT_INDUSTRIAL_ZONE',
}
-- P0-L1 ordinary identity extension; NOT newly approved D/Tier coverage.
-- Named native/HD/JNR construction definitions reviewed; one-per-player alone
-- is not a Wonder predicate (e.g. ordinary government buildings/Data Center).
local ordinaryOnly={
 ['BUILDING_MONUMENT']='DISTRICT_CITY_CENTER',
 ['BUILDING_GRANARY']='DISTRICT_CITY_CENTER',
 ['BUILDING_WATER_MILL']='DISTRICT_CITY_CENTER',
 ['BUILDING_NILOMETER_HD']='DISTRICT_CITY_CENTER',
 ['BUILDING_PALGUM']='DISTRICT_CITY_CENTER',
 ['BUILDING_WALLS']='DISTRICT_CITY_CENTER',
 ['BUILDING_CASTLE']='DISTRICT_CITY_CENTER',
 ['BUILDING_STAR_FORT']='DISTRICT_CITY_CENTER',
 ['BUILDING_TSIKHE']='DISTRICT_CITY_CENTER',
 ['BUILDING_EXHIBITION']='DISTRICT_CITY_CENTER',
 ['BUILDING_FLOOD_BARRIER']='DISTRICT_CITY_CENTER',
 ['BUILDING_HD_POLICE_STATION']='DISTRICT_CITY_CENTER',
 ['BUILDING_HD_TABLES_OF_LAW']='DISTRICT_CITY_CENTER',
 ['BUILDING_HANGAR']='DISTRICT_AERODROME',
 ['BUILDING_AIRPORT']='DISTRICT_AERODROME',
 ['BUILDING_SEWER']='DISTRICT_AQUEDUCT',
 ['BUILDING_HD_HYDRAULIC_SPINNING_WHEEL']='DISTRICT_AQUEDUCT',
 ['BUILDING_JNR_BATHHOUSE']='DISTRICT_AQUEDUCT',
 ['BUILDING_JNR_HAMMER_WORKS']='DISTRICT_AQUEDUCT',
 ['BUILDING_JNR_ORCHARD']='DISTRICT_AQUEDUCT',
 ['BUILDING_HYDROELECTRIC_DAM']='DISTRICT_DAM',
 ['BUILDING_ARENA']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_ZOO']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_STADIUM']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_THERMAL_BATH']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_TLACHTLI']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_HD_SALON']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_JNR_BOTANICAL_GARDEN']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_JNR_THEME_PARK']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_JNR_TOURNEY']='DISTRICT_ENTERTAINMENT_COMPLEX',
 ['BUILDING_FERRIS_WHEEL']='DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
 ['BUILDING_AQUARIUM']='DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
 ['BUILDING_AQUATICS_CENTER']='DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
 ['BUILDING_JNR_CASINO']='DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
 ['BUILDING_JNR_FOOD_COURT']='DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
 ['BUILDING_JNR_MARINA']='DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
 ['BUILDING_GROVE']='DISTRICT_PRESERVE',
 ['BUILDING_SANCTUARY']='DISTRICT_PRESERVE',
 ['BUILDING_HD_CULTURE_HERITAGE_PRESERVE']='DISTRICT_PRESERVE',
 ['BUILDING_HD_LANDFORM_EPO']='DISTRICT_PRESERVE',
 ['BUILDING_HD_RESOURCE_EPO']='DISTRICT_PRESERVE',
 ['BUILDING_HD_SCENIC_EPO']='DISTRICT_PRESERVE',
 ['BUILDING_HD_SPECIES_EPO']='DISTRICT_PRESERVE',
 ['BUILDING_FISH_MARKET']='DISTRICT_HARBOR',
 ['BUILDING_LIGHTHOUSE_FISHING']='DISTRICT_HARBOR',
 ['BUILDING_OFFSHORE_TERMINAL']='DISTRICT_HARBOR',
 ['BUILDING_JNR_ENTREPOT']='DISTRICT_HARBOR',
 ['BUILDING_HD_ALCHEMY_ROOM']='DISTRICT_HOLY_SITE',
 ['BUILDING_EL_ESCORIAL_PALACE']='DISTRICT_GOVERNMENT',
 ['BUILDING_HD_HUMAN_RIGHTS_COUNCIL']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSE']='DISTRICT_DIPLOMATIC_QUARTER',
}
local domains={
 ['DISTRICT_CAMPUS']=true,
 ['DISTRICT_INDUSTRIAL_ZONE']=true,
 ['DISTRICT_THEATER']=true,
 ['DISTRICT_COMMERCIAL_HUB']=true,
 ['DISTRICT_HARBOR']=true,
 ['DISTRICT_ENCAMPMENT']=true,
 ['DISTRICT_HOLY_SITE']=true,
 ['DISTRICT_GOVERNMENT']=true,
 ['DISTRICT_DIPLOMATIC_QUARTER']=true,
 ['DISTRICT_NEIGHBORHOOD']=true,
}
local function flag(v) return v==true or v==1 end
function M.Build(P)
 local hd=assert(P.Field(GameInfo,'HD_BuildingTiers'),'DC_HD_TIERS_UNAVAILABLE')
 local dummyTable=assert(P.Field(GameInfo,'HD_DUMMY_BUILDINGS'),'DC_HD_DUMMY_TABLE_UNAVAILABLE')
 local tiers,dummy,replaces,dr={},{},{},{}
 for r in hd() do tiers[r.BuildingType]=r end
 for r in dummyTable() do dummy[r.BuildingType]=true end
 for r in GameInfo.DistrictReplaces() do dr[r.CivUniqueDistrictType]=r.ReplacesDistrictType end
 for r in GameInfo.BuildingReplaces() do
  replaces[r.CivUniqueBuildingType]=replaces[r.CivUniqueBuildingType] or {}
  table.insert(replaces[r.CivUniqueBuildingType],r.ReplacesBuildingType)
 end
 local out={revision=M.REVISION,buildings={}}
 function out.District(kind)
  local seen={}
  while dr[kind] do if seen[kind] then return nil end;seen[kind]=true;kind=dr[kind] end
  return kind
 end
 function out.Domain(kind)
  local base=out.District(kind);return domains[base] and base or nil
 end
 local function tier(kind,seen)
  if seen[kind] then return nil,'REPLACEMENT_CYCLE' end;seen[kind]=true
  local row=tiers[kind];local raw=row and row.Tier
  if raw~=nil and (type(raw)~='number' or raw%1~=0 or raw<0 or raw>4) then return nil,'TIER_UNSUPPORTED' end
  local normalized
  for _,base in ipairs(replaces[kind] or {}) do
   if not known[base] or known[base]~=known[kind] then return nil,'REPLACEMENT_UNREVIEWED' end
   local n,err=tier(base,seen);seen[base]=nil
   if n==nil then return nil,err end
   if normalized~=nil and normalized~=n then return nil,'REPLACEMENT_TIER_CONFLICT' end
   normalized=n
  end
  if normalized~=nil and raw~=nil and raw~=normalized then return nil,'REPLACEMENT_TIER_CONFLICT' end
  if row and out.Domain(row.PrereqDistrict)~=known[kind] then return nil,'TIER_DISTRICT_CONFLICT' end
  return normalized or raw,(normalized~=nil and 'REPLACEMENT_TIER' or 'HD_TIER')
 end
 for b in GameInfo.Buildings() do
  local r={type=b.BuildingType,index=b.Index,name=b.Name,domain=out.Domain(b.PrereqDistrict),ordinaryDistrict=out.District(b.PrereqDistrict),ordinary=false}
  if b.BuildingType=='BUILDING_PALACE' then r.reason='PALACE'
  elseif flag(b.IsWonder) then r.reason='WONDER'
  elseif flag(b.InternalOnly) or dummy[b.BuildingType] or b.BuildingType:match('^BUILDING_SPC_') then r.reason='INTERNAL_OR_TECHNICAL'
  elseif ordinaryOnly[b.BuildingType] then
   if r.ordinaryDistrict~=ordinaryOnly[b.BuildingType] then r.reason='DISTRICT_CLASSIFICATION_CONFLICT'
   else r.ordinary=true;r.depthEligible=false;r.reason='ORDINARY_DEPTH_NOT_REVIEWED' end
  elseif not known[b.BuildingType] then r.reason='UNREVIEWED_BUILDING'
  elseif r.domain~=known[b.BuildingType] then r.reason='DISTRICT_CLASSIFICATION_CONFLICT'
  else
   r.ordinary=true;r.tier,r.tierSource=tier(b.BuildingType,{})
   if r.tier==nil then r.reason=r.tierSource=='HD_TIER' and 'TIER_UNKNOWN' or r.tierSource
   else r.reason=r.tier==0 and 'ORDINARY_TIER_ZERO' or 'ELIGIBLE' end
  end
  r.ordinaryReason=r.ordinary and 'ELIGIBLE' or r.reason
  out.buildings[b.Index]=r;out.buildings[b.BuildingType]=r
 end
 return out
end
