-- P0-A: reviewed ordinary ontology, NOT Standardization activation policy.
-- Supported named base/HD infrastructure only; unknown rows never auto-enroll.
-- Native/HD tier data is adapter evidence. No database writes or yield carriers.
SPCOrdinaryBuildingCatalog={}
local M=SPCOrdinaryBuildingCatalog
M.REVISION='D0035-P0B2-1'
local known={
 ['BUILDING_FAIR']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_HD_ART_PUBLISHING_HOUSE']='DISTRICT_THEATER',
 ['BUILDING_HD_DATA_CENTER']='DISTRICT_CAMPUS',
 ['BUILDING_HD_ELECTRONICS_FACTORY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_HD_INTERNET_COMPANY']='DISTRICT_INDUSTRIAL_ZONE',

 ['BUILDING_AMPHITHEATER']='DISTRICT_THEATER',
 ['BUILDING_ARMORY']='DISTRICT_ENCAMPMENT',
 ['BUILDING_BANK']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_BARRACKS']='DISTRICT_ENCAMPMENT',
 ['BUILDING_BASILIKOI_PAIDES']='DISTRICT_ENCAMPMENT',
 ['BUILDING_BROADCAST_CENTER']='DISTRICT_THEATER',
 ['BUILDING_CATHEDRAL']='DISTRICT_HOLY_SITE',
 ['BUILDING_CHANCERY']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_COAL_POWER_PLANT']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_CONSULATE']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_DAR_E_MEHR']='DISTRICT_HOLY_SITE',
 ['BUILDING_ELECTRONICS_FACTORY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_FACTORY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_FILM_STUDIO']='DISTRICT_THEATER',
 ['BUILDING_FOOD_MARKET']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_FOSSIL_FUEL_POWER_PLANT']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_GOV_CITYSTATES']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_CONQUEST']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_CULTURE']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_FAITH']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_MILITARY']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_SCIENCE']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_SPIES']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_TALL']='DISTRICT_GOVERNMENT',
 ['BUILDING_GOV_WIDE']='DISTRICT_GOVERNMENT',
 ['BUILDING_GRAND_BAZAAR']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_GURDWARA']='DISTRICT_HOLY_SITE',
 ['BUILDING_HD_INN']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_HD_REGIONAL_COUNCIL_CENTER']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_HD_TAVERN']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS']='DISTRICT_DIPLOMATIC_QUARTER',
 ['BUILDING_IZ_WATER_MILL']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_ACADEMY']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_ALTAR']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_ARCHITECTURE']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_ARSENAL']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_ART_GALLERY']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_ASSEMBLY']='DISTRICT_THEATER',
 ['BUILDING_JNR_CABINET']='DISTRICT_THEATER',
 ['BUILDING_JNR_CANDI']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_CAVALIER']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_CHEMICAL']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_COMMODITY_EXCHANGE']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_CRUISE_TERMINAL']='DISTRICT_HARBOR',
 ['BUILDING_JNR_DAOGUAN']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_DEPOT']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_EDUCATION']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_FREEPORT']='DISTRICT_HARBOR',
 ['BUILDING_JNR_FREIGHT_YARD']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_GARDEN']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_GRAND_HOTEL']='DISTRICT_THEATER',
 ['BUILDING_JNR_GUILDHALL']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_HAVEN']='DISTRICT_HARBOR',
 ['BUILDING_JNR_HOSPITAL']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_HOSPITIUM']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_JINJA']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_KHALWAT']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_LABORATORY']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_LIBERAL_ARTS']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_LIGHTHOUSE_TRADE']='DISTRICT_HARBOR',
 ['BUILDING_JNR_MANDIR']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_MANSION']='DISTRICT_THEATER',
 ['BUILDING_JNR_MANUFACTURY']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_MARKETING_AGENCY']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_MBARI']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_MEDIA_CENTER']='DISTRICT_THEATER',
 ['BUILDING_JNR_MEDITATION']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_MERCHANT_QUARTER']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_MINT']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_MONASTERY']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_NAVAL_BASE']='DISTRICT_HARBOR',
 ['BUILDING_JNR_OPERA']='DISTRICT_THEATER',
 ['BUILDING_JNR_PERIPTEROS']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_PRISON']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_REAL_ACADEMY']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_RECYCLING_PLANT']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_SCHOOL']='DISTRICT_CAMPUS',
 ['BUILDING_JNR_SOBOR']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_TARGET_RANGE']='DISTRICT_ENCAMPMENT',
 ['BUILDING_JNR_TOOLING_SHOP']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_JNR_TRANSIT_HUB']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_JNR_TZACUALLI']='DISTRICT_HOLY_SITE',
 ['BUILDING_JNR_WAYSTATION']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_JNR_WIND_MILL']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_LIBRARY']='DISTRICT_CAMPUS',
 ['BUILDING_LIGHTHOUSE']='DISTRICT_HARBOR',
 ['BUILDING_MADRASA']='DISTRICT_CAMPUS',
 ['BUILDING_MARAE']='DISTRICT_THEATER',
 ['BUILDING_MARKET']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_MEETING_HOUSE']='DISTRICT_HOLY_SITE',
 ['BUILDING_MILITARY_ACADEMY']='DISTRICT_ENCAMPMENT',
 ['BUILDING_MOSQUE']='DISTRICT_HOLY_SITE',
 ['BUILDING_MUSEUM_ART']='DISTRICT_THEATER',
 ['BUILDING_MUSEUM_ARTIFACT']='DISTRICT_THEATER',
 ['BUILDING_NAVIGATION_SCHOOL']='DISTRICT_CAMPUS',
 ['BUILDING_ORDU']='DISTRICT_ENCAMPMENT',
 ['BUILDING_PAGODA']='DISTRICT_HOLY_SITE',
 ['BUILDING_POWER_PLANT']='DISTRICT_INDUSTRIAL_ZONE',
 ['BUILDING_PRASAT']='DISTRICT_HOLY_SITE',
 ['BUILDING_QUEENS_BIBLIOTHEQUE']='DISTRICT_GOVERNMENT',
 ['BUILDING_RESEARCH_LAB']='DISTRICT_CAMPUS',
 ['BUILDING_SEAPORT']='DISTRICT_HARBOR',
 ['BUILDING_SHIPYARD']='DISTRICT_HARBOR',
 ['BUILDING_SHOPPING_MALL']='DISTRICT_NEIGHBORHOOD',
 ['BUILDING_SHRINE']='DISTRICT_HOLY_SITE',
 ['BUILDING_STABLE']='DISTRICT_ENCAMPMENT',
 ['BUILDING_STAVE_CHURCH']='DISTRICT_HOLY_SITE',
 ['BUILDING_STOCK_EXCHANGE']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_STUPA']='DISTRICT_HOLY_SITE',
 ['BUILDING_SUKIENNICE']='DISTRICT_COMMERCIAL_HUB',
 ['BUILDING_SYNAGOGUE']='DISTRICT_HOLY_SITE',
 ['BUILDING_TEMPLE']='DISTRICT_HOLY_SITE',
 ['BUILDING_UNIVERSITY']='DISTRICT_CAMPUS',
 ['BUILDING_WAT']='DISTRICT_HOLY_SITE',
 ['BUILDING_WORKSHOP']='DISTRICT_INDUSTRIAL_ZONE',
}
local domains={
 ['DISTRICT_CAMPUS']=true,
 ['DISTRICT_INDUSTRIAL_ZONE']=true,
 ['DISTRICT_THEATER']=true,
 ['DISTRICT_COMMERCIAL_HUB']=true,
 ['DISTRICT_HARBOR']=true,
 ['DISTRICT_ENCAMPMENT']=true,
 ['DISTRICT_HOLY_SITE']=true,
 ['DISTRICT_GOVERNMENT']=true,
 ['DISTRICT_DIPLOMATIC_QUARTER']=true,
 ['DISTRICT_NEIGHBORHOOD']=true,
}
local function flag(v) return v==true or v==1 end
function M.Build(P)
 local hd=assert(P.Field(GameInfo,'HD_BuildingTiers'),'DC_HD_TIERS_UNAVAILABLE')
 local dummyTable=assert(P.Field(GameInfo,'HD_DUMMY_BUILDINGS'),'DC_HD_DUMMY_TABLE_UNAVAILABLE')
 local tiers,dummy,replaces,dr={},{},{},{}
 for r in hd() do tiers[r.BuildingType]=r end
 for r in dummyTable() do dummy[r.BuildingType]=true end
 for r in GameInfo.DistrictReplaces() do dr[r.CivUniqueDistrictType]=r.ReplacesDistrictType end
 for r in GameInfo.BuildingReplaces() do
  replaces[r.CivUniqueBuildingType]=replaces[r.CivUniqueBuildingType] or {}
  table.insert(replaces[r.CivUniqueBuildingType],r.ReplacesBuildingType)
 end
 local out={revision=M.REVISION,buildings={}}
 function out.Domain(kind)
  local seen={}
  while dr[kind] do if seen[kind] then return nil end;seen[kind]=true;kind=dr[kind] end
  return domains[kind] and kind or nil
 end
 local function tier(kind,seen)
  if seen[kind] then return nil,'REPLACEMENT_CYCLE' end;seen[kind]=true
  local row=tiers[kind];local raw=row and row.Tier
  if raw~=nil and (type(raw)~='number' or raw%1~=0 or raw<0 or raw>4) then return nil,'TIER_UNSUPPORTED' end
  local normalized
  for _,base in ipairs(replaces[kind] or {}) do
   if not known[base] or known[base]~=known[kind] then return nil,'REPLACEMENT_UNREVIEWED' end
   local n,err=tier(base,seen);seen[base]=nil
   if n==nil then return nil,err end
   if normalized~=nil and normalized~=n then return nil,'REPLACEMENT_TIER_CONFLICT' end
   normalized=n
  end
  if normalized~=nil and raw~=nil and raw~=normalized then return nil,'REPLACEMENT_TIER_CONFLICT' end
  if row and out.Domain(row.PrereqDistrict)~=known[kind] then return nil,'TIER_DISTRICT_CONFLICT' end
  return normalized or raw,(normalized~=nil and 'REPLACEMENT_TIER' or 'HD_TIER')
 end
 for b in GameInfo.Buildings() do
  local r={type=b.BuildingType,index=b.Index,name=b.Name,domain=out.Domain(b.PrereqDistrict),ordinary=false}
  if b.BuildingType=='BUILDING_PALACE' then r.reason='PALACE'
  elseif flag(b.IsWonder) then r.reason='WONDER'
  elseif flag(b.InternalOnly) or dummy[b.BuildingType] or b.BuildingType:match('^BUILDING_SPC_') then r.reason='INTERNAL_OR_TECHNICAL'
  elseif not known[b.BuildingType] then r.reason='UNREVIEWED_BUILDING'
  elseif r.domain~=known[b.BuildingType] then r.reason='DISTRICT_CLASSIFICATION_CONFLICT'
  else
   r.ordinary=true;r.tier,r.tierSource=tier(b.BuildingType,{})
   if r.tier==nil then r.reason=r.tierSource=='HD_TIER' and 'TIER_UNKNOWN' or r.tierSource
   else r.reason=r.tier==0 and 'ORDINARY_TIER_ZERO' or 'ELIGIBLE' end
  end
  out.buildings[b.Index]=r;out.buildings[b.BuildingType]=r
 end
 return out
end
